prepare:
  test_frac: 0.25
  categorical_columns:
    - pclass
    - sex
    - embarked
  numerical_columns:
    - age
    - sibsp
    - parch
    - fare

train:
  clf:
    seed:
      - 42
    n_estimators:
      - 500
      - 1000
  ohe:
    handle_unknown:
      - ignore
  imputer:
    strategy:
      - mean
  categoricals:
    - pclass
    - sex
    - embarked
  numericals:
    - age
    - sibsp
    - parch
    - fare
