name: CI

on: 
  push:
    branches:    
      - main 
  pull_request:
    branches:
      - main

jobs:
  cirun:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Upgrade python-pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies        
        run: pip install dvc tox
      - name: Get data
        run: make get-data
      - name: Initialize DVC
        run: dvc init
      - name: Run DVC pipeline
        run: make dvc-run-pipe
      - name: Run tests and show summary
        run: make tests
        env:
          SHOW_COV_HTML: False
      - name: Retrieve git history
        run: git fetch --prune
      - name: Show diff in pipeline step params and in scoring metrics as a Markdown report
        run: |
          echo "## Model parameters and scoring metrics" > report.md
          dvc params diff --show-md main >> report.md
          dvc metrics diff --show-md main >> report.md
      - name: Send report
        run: cml-send-comment report.md
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean test artifacts
        run: make clean-tests
