name: CI

on: [push]

jobs:
  cirun:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Upgrade python-pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies        
        run: pip install dvc tox
      - name: Get data
        run: make data
      - name: Initialize DVC
        run: dvc init
      - name: Run DVC pipeline
        run: make dvc-run-pipe
      - name: Run tests and show summary
        run: make tests
      - env:
          SHOW_COV_HTML: False
      # - name: Retrieve git history
      #   run: git fetch --prune
      # - name: Show diff in scoring metric as a Markdown report
      #   run: dvc metrics diff --show-md main > report.md
      # - name: Send report
      #   run: cml-send-comment report.md
